# Generated by Django 5.1.4 on 2024-12-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album_title', models.CharField(max_length=500)),
                ('artist_name', models.CharField(max_length=500)),
                ('release_year', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=500)),
                ('inclusions', models.CharField(max_length=1000)),
            ],
        ),
    ]
